### ISSUE TITLE
Problem with emacsclient and Windows

### ISSUE THREAD

**Issue by fpopineau** [magit/with-editor#24] opened 2017-03-17 14:23 UTC
Under Windows, emacsclient has the (bad) property of not writing anything on the console, but rather reporting any output in a modal window. So the automatic detection fails. Any idea on how to solve this?
Also I'm not sure that the sleeping editor would work under Windows.

**Comment by tarsius** [comment] 2017-03-17 14:50
@npostavs will hopefully have an answer for that. I don't know much about this, since I don't use Windows. All I can say is that it probably depends on what emacsclient executable (or wrapper script?) is used because for the majority of Windows users this works as intended.

It might also depend on the exact version of an involved programs, which is why you should not have ignored the issue template and have provided that information upfront, as requested. Also this actually is the wrong repository for this sort of question, because it is about `with-editor`.

**Comment by fpopineau** [comment] 2017-03-17 14:56
Actually, I wonder how it can work for Windows users. The emacsclient program is compiled to behave in such a way that if it is run from emacs, it considers to be a gui app, so it does not write its version on stdout but it uses a MessageBox() to report it. Running magit, I got 8 such dialog boxes showing "Emacs 25.2" and the message about being unable to find a suitable emacsclient.
I have recompiled to emacsclient to avoid using those dialog boxes and always report on stdout.
And now it does work.
I will ask on emacs-devel about the rationale of keeping those dialog boxes.

**Comment by npostavs** [comment] 2017-03-17 14:57
> Under Windows, emacsclient has the (bad) property of not writing anything on the console, but rather reporting any output in a modal window

emacsclient.exe writes to the console, emacsclientw.exe opens a window (because it doesn't open a console).

```
C:\Users\npostavs>emacsclient --version
emacsclient 24.5
```

**Comment by fpopineau** [comment] 2017-03-17 14:59
Ok. But it is not what you get anymore with emacs-25.

**Comment by npostavs** [comment] 2017-03-17 15:00
> Ok. But it is not what you get anymore with emacs-25.

Yes it is.
```
C:\Users\npostavs>c:\emacs-25.1\bin\emacsclient.exe --version
emacsclient 25.1
```

**Comment by fpopineau** [comment] 2017-03-17 15:04
I get a MessageBox() reporting emacs 25.2.
If I look at emacsclient.c:
- the message() function chooses to use a MessageBox() or to print on stdout depending on what w32_window_app() reports
- w32_window_app() is looking at the console title to guess it is running in a console or elsewhere.
Could that be because I'm running Windows 10 that I don't see the same thing you see ?

**Comment by npostavs** [comment] 2017-03-17 15:19
Same result with 25.2, Windows 10.

```
C:\Users\npostavs\src\emacs\emacs-25>lib-src\emacsclient.exe --version
emacsclient 25.2
```

Are you using some kind of fancy console?

**Comment by npostavs** [comment] 2017-04-02 19:14
According to https://github.com/magit/with-editor/issues/21#issuecomment-273648651, this is a bug which is specific to certain versions of Windows 10.

**Comment by tarsius** [comment] 2017-05-17 03:32
Closing as a duplicate of #21.

**Closed by tarsius** 2017-05-17 03:32 UTC
Labels: support
